package com.example.cosc3p97_groupproject;


/** Class that holds 3 arrays for 3 categories of healthiness, and includes common ingredients and additives
 *
 * @author Mason De Fazio and Chris Orr
 * @course      COSC 3P97
 * @version     1.0  */
public class Ingredients {

    public static final String [] unHealthy3 = {
            "Sodium Nitrate",
            "Sulfites",
            "Azodicarbonamide",
            "Potassium bromate",
            "Propyl gallate",
            "BHA/BHT",
            "Propylene glycol",
            "Butane",
            "Monosodium glutamate",
            "Disodium inosinate",
            "Disodium guanylate",
            "Recombinant Bovine Growth Hormone",
            "Refined vegetable oil",
            "Sodium benzoate",
            "Brominated vegetable oil",
            "Propyl gallate",
            "Olestra",
            "Carrageenan",
            "Polysorbate 60",
            "Camauba wax",
            "Magnesium sulphate",
            "Chlorine dioxide",
            "Paraben",
            "Sodium carboxymethyl cellulose",
            "Aluminum",
            "Saccharin",
            "Aspartame",
            "High fructose corn syrup",
            "Acesulfame potassium",
            "Sucralose",
            "Agave nectar",
            "Bleached starch",
            "Tert butylhydroquinone",
            "Red #40",
            "Blue #1",
            "Blue #2",
            "Citrus red #1",
            "Citrus red #2",
            "Green #3",
            "Yellow #5",
            "Yellow #6",
            "Red #2",
            "Red #3",
            "Caramel coloring",
            "Brown HT",
            "Orange B",
            "Bixin",
            "Norbixin",
            "Annatto",
            "Mason",
            "High-Fructose Corn Syrup",
            "Palm Oil",
            "Corn Syrup",
            "Monosodium Glutamate (MSG)",
            "Artificial Flavors",
            "Artificial Colors",
            "Sodium Benzoate",
            "Carrageenan",
            "TBHQ (Tertiary Butylhydroquinone)",
            "BHA (Butylated Hydroxyanisole)",
            "BHT (Butylated Hydroxytoluene)",
            "Hydrogenated Palm Kernel Oil",
            "Palm Kernel Oil",
            "Soy Sauce",
            "Sorbitol",
            "Artificial Sweeteners"
    };

    public static final String[] unHealthy2 = {
            "MSG",
            "Soybean Oil",
            "Canola Oil",
            "Soy Lecithin",
            "Xanthan Gum",
            "Guar Gum",
            "Calcium Carbonate",
            "Potassium Sorbate",
            "Citric Acid",
            "Carrageenan",
            "Ascorbic Acid (Vitamin C)",
            "Reduced Iron",
            "Thiamine Mononitrate (Vitamin B1)",
            "Riboflavin (Vitamin B2)",
            "Folic Acid (Vitamin B9)",
            "Zinc Oxide",
            "Vitamin D3",
            "Vitamin A Palmitate",
            "Maltodextrin",
            "Calcium Propionate",
            "Yeast Extract",
            "Lactic Acid",
            "Sodium Citrate",
            "Sodium Hexametaphosphate",
            "Sodium Nitrite",
            "Sodium Phosphate",
            "Sodium Tripolyphosphate",
            "Calcium Chloride",
            "Disodium Inosinate",
            "Disodium Guanylate",
            "Corn Syrup Solids",
            "Corn Flour",
            "Corn Oil",
            "Rice Flour",
            "Modified Food Starch",
            "Egg Whites",
            "Egg Yolks",
            "Modified Corn Starch",
            "Enriched wheat flour",
            "Nonfat Milk",
            "Rice Starch",
            "Cocoa",
            "Whole Milk",
            "Skim Milk",
            "Malted Barley Flour",
            "Barley Malt Extract",
            "Malt Extract",
            "Soy Flour",
            "Whey",
            "Wheat Bran",
            "Wheat Germ",
            "Corn Grits",
            "Dried Garlic",
            "Dried Onion",
            "Rice Bran",
            "Rice Syrup",
            "Rice Hulls",
            "Palm Stearin",
            "Palm Olein",
            "Palm Kernel Olein",
            "Palm Kernel Stearin",
            "Cottonseed Oil",
            "Natural flavour"
    };

    public static final String[] healthy = {
            "Salt",
            "Sugar",
            "Flour",
            "Water",
            "Cornstarch",
            "Niacinamide",
            "Cocoa Butter",
            "Cocoa Powder",
            "Pectin",
            "Enriched Corn Meal"
    };




}
